### ISSUE TITLE
Drops connection, needs hard reset

### ISSUE THREAD

**Issue by ron7136** [ubidots/ubidots-particle#18]
I thought the was a problem with Photon as all mine needed hard reset every few hours until I switched from ubidots to thingspeak. Somehow the ubidots lib is causing the Photon to lose connection to the network. The problem is worst on the Photons farthest from the router i.e. have weak wifi signal.

**Comment by Metavix** [comment]
Hello @ron7136  how are you?
Wow that is interesting, i will check our library and do some test to it. Maybe is a library problem. Thank you for report it

**Comment by Metavix** [comment]
@ron7136 What version were you using? and Could you paste here your code please?

**Comment by ron7136** [comment]
Ver was 2.1.5 Just updated to 2.1.6

// This #include statement was automatically added by the Particle IDE.
#include "Ubidots/Ubidots.h"

// This #include statement was automatically added by the Particle IDE.
#include "OneWire/OneWire.h"

// This #include statement was automatically added by the Particle IDE.
#include "spark-dallas-temperature/spark-dallas-temperature.h"

#define ONE_WIRE_BUS D2
OneWire oneWire(ONE_WIRE_BUS);
DallasTemperature sensor(&oneWire);

#define TOKEN "xxxxxxxxxxxxxxxxxxxxxxxx"
#define DATASOURCE_NAME "RJW7"

Ubidots ubidots(TOKEN);

int volatile send_data_ind = 1;

Timer timer1(60000, send_temp);


void setup() {
    RGB.brightness(5);
    sensor.begin();
    timer1.start();
    ubidots.setDatasourceName(DATASOURCE_NAME);
    ApplicationWatchdog wd(60000, System.reset);   // set watchdog timer to 60 Sec.
    Particle.publish("Starting up 7.11", System.version() , 60, PRIVATE );
}

void send_temp() {
    send_data_ind = 1;
}

void loop() {
    if (send_data_ind > 0) {
	send_data_ind = 0;     // data sent, reset indicator
	sensor.requestTemperatures();
	delay(1000);
	float temperature = sensor.getTempCByIndex( 0 );
	if (temperature > -60 ) {  // only send if good temp.
	    ubidots.add("Temp7", temperature);
	    ubidots.sendAll(); 
	}
    }
    delay(100);
}

**Comment by Metavix** [comment]
@ron7136  This code with the new version has the same problem?

**Comment by ron7136** [comment]
Testing now, over 24 hrs and still going....
