### ISSUE TITLE
Particle

### ISSUE THREAD

**Issue by ron7136** [ubidots/ubidots-particle#4]
You should mention in the docs that it creates all the variables under the "Particle" data source name. Took me a while to find that! Thanks for all the good work!

**Comment by Metavix** [comment]
Oh it's true I will do that thanx for all

**Comment by ron7136** [comment]
I am using multiple photons now and they all create separate sources with the same  "Particle" data source name.  It makes it hard to tell them apart but the good news is that I can flash the same code to all photons.  One warning, putting a space in a variable name will cause endless flash on SOS and reboot until you go into safe mode to recover. Thanks for the LIB, great work!

**Comment by ron7136** [comment]
One other note. Sending a 0 value will cause the data to be ignored, so if the temp. is 0 it will not be recorded.

**Comment by AgustinPelaez** [comment]
Hey Ron, we're working on a new version of the library based on your suggestions. Thanks for your feedback, will keep you updated.
