### ISSUE TITLE
Examples need some additions 

### ISSUE THREAD

**Issue by leitmecke** [ubidots/ubidots-particle#55]
The examples do only work with a industrial Ubidots account, it seems that this is the predefined standard server. Here's a kind of improvement proposal from me:

You should add the UbiServer argument to the Ubidots definition at the beginning in every example listing, e.g. Ubidots ubidots(UBIDOTS_TOKEN, UBI_EDUCATIONAL, UBI_TCP); otherwise send/get of the values is not working with an eductional account.

Thank you
Greetings from Germany
Christoph

**Comment by jotathebest** [comment]
added.

All the best

**Comment by leitmecke** [comment]
Great! Thank you :)
