### ISSUE TITLE
No change to data source name 

### ISSUE THREAD

**Issue by ron7136** [ubidots/ubidots-particle#8]
![rjw1](https://cloud.githubusercontent.com/assets/17958128/14233695/ca052c4e-f99d-11e5-9047-85629b6f908d.jpg)
This only changes the TAG on the data source not the actual name. "Particle" is the data source name. 

// This #include statement was automatically added by the Particle IDE.
#include "Ubidots/Ubidots.h"

float temperature = 10.0;

#define TOKEN "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define DATASOURCE_NAME "RJW1"

Ubidots ubidots(TOKEN);

void setup() {
}
 
void loop() {
    ubidots.setDatasourceName(DATASOURCE_NAME);
    ubidots.add("Temp_1", temperature);  
    ubidots.sendAll();
    delay(59000);
}

**Comment by ron7136** [comment]
The good news is it works and 

ubidots.getValueWithDatasource(DATASOURCE_NAME, "Name_of_your_variable");

works so I guess it does not really matter about the data source name being all the same.

**Comment by Metavix** [comment]
Yes my friend but you can change the name of the variable in the API,

**Comment by AgustinPelaez** [comment]
Thanks Ron, we'll add support to change the name of the data source soon. Meanwhile, you can change it through the front-end in your Ubidots account.

**Comment by ron7136** [comment]
Found the reason the DatasourceName did not change was because it already existed. Once I deleted it, it then created the correct DatasourceName instead of just the tag.
